plugins {
    id 'com.android.application'
}

android {
	namespace "com.nettv.livestore"
    compileSdkVersion 33

    defaultConfig {
        applicationId 'com.nettv.livestore'
        minSdkVersion 21
        //noinspection ExpiringTargetSdkVersion,ExpiredTargetSdkVersion
        targetSdkVersion 33
        versionCode 40
        versionName "3.8"
        useLibrary 'org.apache.http.legacy'

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    lintOptions {
        abortOnError false
    }

    buildFeatures {
        buildConfig = false
    }
}

dependencies {
    // TODO: dependencies
}
